title: Dream Dress Noivas
email: info@dreamdressnoiva.com
description: >- # this means to ignore newlines until "baseurl:"
  Realizando Sonhos!
url: "https://dreamdressnoiva.com"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-email-protect 
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components
