title: Dream Dress Noivas
email: info@dreamdressnoiva.com
description: >- # this means to ignore newlines until "baseurl:"
  Realizando Sonhos!
url: "https://dreamdressnoiva.com"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-email-protect 
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo.jpeg

snipcart_api_key: OTkzMDk0NTktYmJiNy00MjBlLWI3NDQtMGVlZTg5ZmExZmVkNjM2NTE5MjM1NTA5NjMyMzM3

collections:
  produtos:

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2